---
title: "3rdRoughAnalysis"
author: "Mariko Nakagawa"
date: "2022-08-12"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
### Splicing Signals
I counted each splicing signal in site-based counting. (Count as 1 splicing signal when there are multiple reads crossing an intron.)

I discarded data whose donor and acceptor are unknown.

I also discarded data in which reads have inserted sequence between aligned regions.
``` {r ssFileReading, echo=FALSE}
ss_embryos <- read.table(file="~/biohazard/data/oikopleura/analysis/embryos/splicingSignalDist_countedBySites_embryos.tsv", sep = '\t', header = T)
ss_immature <- read.table(file="~/biohazard/data/oikopleura/analysis/immatureAdults/splicingSignalDist_countedBySites_immatureAdults.tsv", sep = '\t', header = T)
ss_matured <- read.table(file="~/biohazard/data/oikopleura/analysis/maturedAdults/splicingSignalDist_countedBySites_maturedAdults.tsv", sep = '\t', header = T)
```
```{r ssGraph, fig.show='hold', out.width="30%", echo=FALSE}
# --- embryos ----
g_ss_embryos <- ss_embryos %>%
  mutate(donor_acceptor=paste(!!!rlang::syms(c('donor', 'acceptor')), sep='-')) %>% 
  head(n=20) %>% 
  ggplot(aes(x=reorder(x=donor_acceptor, X=count),  y=count, label=scales::comma(count))) + 
  coord_flip() +
  geom_bar(stat='identity') + 
  labs(x='donor-acceptor') + 
  geom_text(hjust=-0.1) +
  labs(title='embryos')
plot(g_ss_embryos)

# --- immature ----
g_ss_immature <- ss_immature %>%
  mutate(donor_acceptor=paste(!!!rlang::syms(c('donor', 'acceptor')), sep='-')) %>% 
  head(n=20) %>% 
  ggplot(aes(x=reorder(x=donor_acceptor, X=count),  y=count, label=scales::comma(count))) + 
  coord_flip() +
  geom_bar(stat='identity') + 
  labs(x='donor-acceptor') + 
  geom_text(hjust=-0.1) +
  labs(title='immature adults')
plot(g_ss_immature)

# --- matured ----
g_ss_matured <- ss_matured %>%
  mutate(donor_acceptor=paste(!!!rlang::syms(c('donor', 'acceptor')), sep='-')) %>% 
  head(n=20) %>% 
  ggplot(aes(x=reorder(x=donor_acceptor, X=count),  y=count, label=scales::comma(count))) + 
  coord_flip() +
  geom_bar(stat='identity') + 
  labs(x='donor-acceptor') + 
  geom_text(hjust=-0.1) +
  labs(title='matured adults')
plot(g_ss_matured)
```