---
title: "num of candidates: cds-cds fusions"
author: "Mariko Nakagawa"
date: "2023-01-25"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(VennDiagram)
```
```{r loadData, echo=FALSE}
embryosDat <- read.table("~/biohazard/data/oikopleura/cds-cds-splits/keys_intronFile_embryos_cds-cds_fusions_ME_10_reads_majorSS_20220914.out")$V1
immAdultsDat <- read.table("~/biohazard/data/oikopleura/cds-cds-splits/keys_intronFile_immatureAdults_cds-cds_fusions_ME_10_reads_majorSS_20220914.json")$V1
matAdultsDat <- read.table("~/biohazard/data/oikopleura/cds-cds-splits/keys_intronFile_maturedAdults_cds-cds_fusions_ME_10_reads_majorSS_20220914.json")$V1
```
```{r draw, echo=FALSE}
area1 <- length(embryosDat)
#print(area1)
area2 <- length(immAdultsDat)
#print(area2)
area3 <- length(matAdultsDat)
#print(area3)
n12 <- length(calculate.overlap(list(embryosDat, immAdultsDat))$a3)
#print(n12)
n23 <- length(calculate.overlap((list(immAdultsDat, matAdultsDat)))$a3)
#print(n23)
n13 <- length(calculate.overlap((list(embryosDat, matAdultsDat)))$a3)
#print(n13)
n123 <- length(calculate.overlap((list(embryosDat, immAdultsDat, matAdultsDat)))$a5)
#print(n123)

venn.plot <- draw.triple.venn(area1, area2, area3, n12, n23, n13, n123, c("embryos", "immature adults", "matured adults"), euler.d = TRUE, scaled = TRUE)
grid.draw(venn.plot)
grid.newpage()

#venn.diagram(
 # x = list(embryosDat, immAdultsDat, matAdultsDat),
  #category.names = c("embryos" , "immature Adults" , "mature Adults")
#)
```
```{r overlaps, echo=FALSE}
overlaps <- calculate.overlap((list(embryosDat, immAdultsDat, matAdultsDat)))
```
### embryos & immature adults & matured adults
```{r in all, echo=FALSE}
print(overlaps$a5)
```
### only in embryos
``` {r only in embryos, echo=FALSE}
print(overlaps$a1)
```
### only in immature adults
``` {r only in immature adults, echo=FALSE}
print(overlaps$a3)
```
### only in matured adults
```{r only in matured adults, echo=FALSE}
print(overlaps$a7)
```
### embryos & immature adults
```{r e and i, echo=FALSE}
print(overlaps$a2)
```
### immature adults & matured adults
```{r i and m, echo=FALSE}
print(overlaps$a6)
```
### embryos & matured adults
```{r e and m, echo=FALSE}
print(overlaps$a4)
```