---
title: "UV mutations"
author: "Mariko Nakagawa"
date: "2024-02-15"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr) # will be used for data manipulation, specifically the arrange function to sort the data by type and then by mutation
library(RColorBrewer)
library(scales) # For percent formatting
```
```{r plotFunctions, echo=FALSE}
plotMutationCounts <- function(file_path, title_name) {
  # Load data
  data <- read.csv(file_path, sep="\t", header=TRUE)
  
  # Ensure 'type' is a factor with the desired order from the start
  data$type <- factor(data$type, levels=c("no_mutation", "insertion", "deletion", "transition", "transversion", "exception"))
  
  # Aggregate counts by 'category' and 'type'
  aggregated_data <- data %>%
    group_by(category, type) %>%
    summarise(total_count = sum(count), .groups = "drop")
  
  # Make sure the 'type' factor levels are preserved after aggregation
  aggregated_data$type <- factor(aggregated_data$type, levels=c("no_mutation", "insertion", "deletion", "transition", "transversion", "exception"))
  
  # Define colors using RColorBrewer's Set2 palette
  color_palette <- brewer.pal(n = length(levels(aggregated_data$type)), name = "Set2")
  
  # Create the plot with reordered categories
  ggplot(aggregated_data, aes(x = reorder(category, -total_count), y = total_count, fill = type)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    scale_fill_manual(values = color_palette) +
    theme_minimal() +
    labs(title = paste0(title_name, ": Mutation/No Mutation Counts by Category and Type"),
         x = "Category", y = "Count") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

plotMutationPercentage <- function(file_path, title_name) {
  # Load data
  data <- read.csv(file_path, sep="\t", header=TRUE)
  
  # Ensure 'type' is a factor with the desired order from the start
  data$type <- factor(data$type, levels=c("no_mutation", "insertion", "deletion", "transition", "transversion", "exception"))
  
  # Aggregate counts by 'category' and 'type'
  aggregated_data <- data %>%
    group_by(category, type) %>%
    summarise(total_count = sum(count), .groups = "drop") 
  
  # Calculate the total sum of counts to use for percentage calculation
  #print(aggregated_data)
  total_sum <- sum(aggregated_data$total_count)
  #print(total_sum)
  
  # Calculate percentage
  aggregated_data <- aggregated_data %>%
    mutate(percentage = total_count / total_sum * 100)
  
  # Make sure the 'type' factor levels are preserved after aggregation
  aggregated_data$type <- factor(aggregated_data$type, levels=c("no_mutation", "insertion", "deletion", "transition", "transversion", "exception"))
  #print(aggregated_data)
  
  # Define colors using RColorBrewer's Set2 palette
  color_palette <- brewer.pal(n = length(levels(aggregated_data$type)), name = "Set2")
  
  # Create the plot with reordered categories and y-axis as percentage
  ggplot(aggregated_data, aes(x = reorder(category, -percentage), y = percentage, fill = type)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    scale_fill_manual(values = color_palette) +
    scale_y_continuous(limits = c(0, 50)) + 
    theme_minimal() +
    labs(title = paste0(title_name, ": Mutation/No Mutation Percentage by Category and Type"),
         x = "Category", y = "Percentage") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

```
```{r drawContGraph, echo=FALSE}
oAlb_oDio_path <- "~/biohazard/data/oikAlb_oikDio/mut_oikAlb2oikDio_one2one_20240226.tsv"
oAlb_oDio_title <- "oikAlb-oikDio"
pBuc_pCan_path <- "~/biohazard/data/phyBuc_pomCan/mut_phyBuc2pomCan_one2one_20240226.tsv"
pBuc_pCan_title <- "phyBuc-pomCan"
oAlb_oVan_path <- "~/biohazard/data/oikAlb_oikVan/mut_oikAlb2oikVan_one2one_20230229.tsv"
oAlb_oVan_title <- "oikAlb-oikVan"
#plotMutationCounts(oAlb_oDio_path, oAlb_oDio_title)
#plotMutationCounts(pBuc_pCan_path, pBuc_pCan_title)
plotMutationPercentage(oAlb_oDio_path, oAlb_oDio_title)
plotMutationPercentage(oAlb_oVan_path, oAlb_oVan_title)
plotMutationPercentage(pBuc_pCan_path, pBuc_pCan_title)
```

