# Configuration for genome download and processing
settings:
  required_args: 7  # Number of required arguments

# Directory paths
paths:
  base_genomes: "/home/mrk/genomes"
  scripts:
    last: "/home/mrk/scripts/last"
  data: "/home/mrk/data"

# NCBI dataset download settings
download:
  includes:
    gff3,
    rna,
    cds,
    protein,
    genome,
    seq-report

# File patterns
patterns:
  # Directory pattern for each organism
  org_dir: "{org_full}"
  
  # Download files
  ncbi_dataset: "ncbi_dataset.zip"
  
  # Generated files
  fasta: "{org_id}*.fna"  # Pattern for matching FASTA files

# Messages
messages:
  download: "--- Downloading {org_full} from NCBIdataset"
  already_downloaded: "{org_full} already downloaded"
  move_files: "--- Move files and delete unnecessary directories"
  running_uvmut: "--- Running uvmut_3spc.sh"

# Error messages
errors:
  arg_count: "You need {arg_num} arguments"
  usage: |
    You'll get one-to-one alignments of org1-org2 and org1-org3.
    The top genome of each alignment .maf file will be org1. org1 should be in the outgroup.
    - today's date
    - org1 accession ID (e.g. 'GCA_023078555.1')
    - org2 accession ID (e.g. 'GCA_900538255.1')
    - org3 accession ID (e.g. 'GCA_024500015.1')
    - org1 full name: genusSpecies (e.g. 'ulvaProlifera')
    - org2 full name: genusSpecies (e.g. 'ulvaMutabilis')
    - org3 full name: genusSpecies (e.g. 'ulvaCompressa')